import Head from "next/head";
import { Footer, Banner } from "@/components";
import styled from "styled-components";

const App = styled.div`
  position: absolute;
  top: 0;
  display: flex;
  overflow: hidden;
  background-color: black;
  background-image: url("homeBg.jpg");
  background-position: center;
  background-size: cover;
  width: 100vw;
  height: auto;
  flex-direction: column;
  align-items: center;
  gap: 0.1rem;
  @media (max-width: 912px) {
    background-image: url("homeBgMobile.jpg");
    height: 160vh;
  }
`;
const Main = styled.main`
  position: relative;
  width: 100vw;
  height: 100vh;
  padding-top: 2rem;
  @media (max-width: 768px) {
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    align-items: center;
    margin-top: 2rem;
  }
  @media (max-width: 380px) {
    padding-top: 0;
  }
`;
const Image = styled.img`
  display: none;
  @media (max-width: 912px) {
    position: absolute;
    display: block;
    margin-left: 14rem;
  }
  @media (max-width: 768px) {
    position: relative;
    display: block;
    width: 20rem;
    height: auto;
  }
  @media (max-width: 380px) {
    margin-left: -6rem;
  }
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Crypto App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <App>
        <Main>
          <Image src="illustrationMobile.png" />
          <Banner />
        </Main>
        <Footer />
      </App>
    </>
  );
}
